# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  # say-hello:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Say hello"
  #         command: "echo Hello, World!"
  # print-hello:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Print Hello"
  #         command: "echo Hello"
  # print-world:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Print World"
  #         command: "echo World"
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Echo my project settiing env var"
          command: echo "Text to output here" > output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
    - checkout
    - attach_workspace:
       at: ~/
    - run:
        name: "Print out file persisted to workspace"
        command: cat ~/output.txt
workflows:
  say-hello-workflow:
    jobs:
      # - say-hello
      # - print-hello
      # - print-world:
      #     requires:
      #       - print-hello
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
